let nome = window.prompt('Digite Seu nome: ')
let nota_1 = window.prompt('Digite a Nota do Primeiro Bimestre: ')
let nota_2 = window.prompt('Digite a Nota do Segundo Bimestre: ')
let nota_3 = window.prompt('Digite a Nota do Terceiro Bimestre: ')
let nota_4 = window.prompt('Digite a Nota do Quarto Bimestre: ')

console.log(`A nota do Primeiro Bimestre é: ${nota_1}`)
console.log(`A nota do Segundo Bimestre é: ${nota_2}`)
console.log(`A nota do Terceiro Bimestre é: ${nota_3}`)
console.log(`A nota do Quarto Bimestre é: ${nota_4}`)